In [4]:
import numpy as np

In [6]:
arreglo_0_a_99_grados = np.array([0,30,45,60,90])

In [7]:
radianes = arreglo_0_a_99_grados * np.pi/180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [8]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [9]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [13]:
arreglo_random = np.random.randint(0,11,3)
arreglo_random

array([6, 1, 9])

In [14]:
arreglo_random.mean()

5.333333333333333

In [15]:
np.median(arreglo_random)

6.0

In [16]:
np.std(arreglo_random)

3.299831645537222

In [17]:
np.var(arreglo_random)

10.888888888888891

In [18]:
np.mean(arreglo_random)

5.333333333333333