In [3]:
import numpy as np

In [7]:
arreglo_cero_diez = np.arange (11) ** 2
arreglo_cero_diez

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
arreglo_cero_diez[:-3]

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [9]:
arreglo_cero_diez[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [12]:
arreglo_cero_diez[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [13]:
arreglo_cero_diez[::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)