In [2]:
import numpy as np

In [5]:
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.zeros([4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones([5,9])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(-5,1)

array([-5, -4, -3, -2, -1,  0])

In [19]:
arreglo_pares = np.arange(0,20,2)

In [23]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [26]:
arreglo_pares.shape
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [27]:
arreglo_pares.reshape(2, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [30]:
arreglo_veinticuatro = np.arange(24)
arreglo_veinticuatro.shape

(24,)

In [45]:
arreglo_veinticuatro.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [31]:
arreglo_veinticuatro.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [32]:
arreglo_veinticuatro.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [33]:
arreglo_veinticuatro.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [34]:
arreglo_veinticuatro.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [35]:
arreglo_veinticuatro.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [36]:
arreglo_veinticuatro.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
arreglo_veinticuatro.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [41]:
arreglo_veinticuatro.reshape(2,6,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [42]:
arreglo_veinticuatro.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
arreglo_veinticuatro.reshape(2,2,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [68]:
a = np.array([10,10,10])
b = np.array([5,5,5])

#suma
a + b

array([15, 15, 15])

In [ ]:
#resta
a - b

In [ ]:
#multiplicacion
a * b

In [51]:
#division
a / b

array([2., 2., 2.])

In [61]:
#Mod
a % b

array([0, 0, 0], dtype=int32)

In [56]:
uno = np.arange(-5, 39, 0.7363).reshape(5,2,2,3)
dos = np.arange(-5, 39, 0.7363).reshape(5,2,2,3)

In [57]:
uno + dos

array([[[[-10.    ,  -8.5274,  -7.0548],
         [ -5.5822,  -4.1096,  -2.637 ]],

        [[ -1.1644,   0.3082,   1.7808],
         [  3.2534,   4.726 ,   6.1986]]],


       [[[  7.6712,   9.1438,  10.6164],
         [ 12.089 ,  13.5616,  15.0342]],

        [[ 16.5068,  17.9794,  19.452 ],
         [ 20.9246,  22.3972,  23.8698]]],


       [[[ 25.3424,  26.815 ,  28.2876],
         [ 29.7602,  31.2328,  32.7054]],

        [[ 34.178 ,  35.6506,  37.1232],
         [ 38.5958,  40.0684,  41.541 ]]],


       [[[ 43.0136,  44.4862,  45.9588],
         [ 47.4314,  48.904 ,  50.3766]],

        [[ 51.8492,  53.3218,  54.7944],
         [ 56.267 ,  57.7396,  59.2122]]],


       [[[ 60.6848,  62.1574,  63.63  ],
         [ 65.1026,  66.5752,  68.0478]],

        [[ 69.5204,  70.993 ,  72.4656],
         [ 73.9382,  75.4108,  76.8834]]]])

In [58]:
uno - dos

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [59]:
uno * dos

array([[[[2.50000000e+01, 1.81791377e+01, 1.24425508e+01],
         [7.79023921e+00, 4.22220304e+00, 1.73844225e+00]],

        [[3.38956840e-01, 2.37468100e-02, 7.92812160e-01],
         [2.64615289e+00, 5.58376900e+00, 9.60566049e+00]]],


       [[[1.47118274e+01, 2.09022696e+01, 2.81769872e+01],
         [3.65359802e+01, 4.59792486e+01, 5.65067924e+01]],

        [[6.81186116e+01, 8.08147061e+01, 9.45950760e+01],
         [1.09459721e+02, 1.25408642e+02, 1.42441838e+02]]],


       [[[1.60559309e+02, 1.79761056e+02, 2.00047078e+02],
         [2.21417376e+02, 2.43871949e+02, 2.67410797e+02]],

        [[2.92033921e+02, 3.17741320e+02, 3.44532995e+02],
         [3.72408944e+02, 4.01369170e+02, 4.31413670e+02]]],


       [[[4.62542446e+02, 4.94755498e+02, 5.28052824e+02],
         [5.62434426e+02, 5.97900304e+02, 6.34450457e+02]],

        [[6.72084885e+02, 7.10803589e+02, 7.50606568e+02],
         [7.91493822e+02, 8.33465352e+02, 8.76521157e+02]]],


       [[[9.20661238e+02, 9.6588

In [60]:
uno / dos

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [62]:
a * 10

array([100, 100, 100])

In [63]:
a + 7

array([17, 17, 17])

In [67]:
a - 2

70

In [69]:
a / 2

array([5., 5., 5.])

In [70]:
a % 3

array([1, 1, 1], dtype=int32)

In [73]:
arreglo_muestra = np.arange(20).reshape(5,2,2)
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [108]:
respuesta = arreglo_muestra > 6
respuesta2 = arreglo_muestra[respuesta] < 14
respuesta3 = arreglo_muestra[respuesta][respuesta2] % 2 == 0

In [110]:
arreglo_muestra[respuesta][respuesta2][respuesta3]

array([ 8, 10, 12])

In [111]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [113]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [114]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [115]:
np.dot(A, B)

array([[ 6,  7],
       [26, 31]])

In [116]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [117]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
arreglo_doce.sum()

66

In [119]:
arreglo_doce.min()

0

In [120]:
arreglo_doce.max()

11

In [142]:
arreglo_doce = arreglo_doce.reshape(3,2,2)
arreglo_doce

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [141]:
arreglo_doce.shape

(3, 2, 2)

In [133]:
arreglo_doce.sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [134]:
arreglo_doce.sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [135]:
arreglo_doce.sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])